#!/usr/bin/env python3
import requests
import json
import os

CONFIG_PATH = "config.json"
GRAPHQL_URL = "https://leetcode.com/graphql"

with open(CONFIG_PATH) as f:
    cfg = json.load(f)

USERNAME = cfg["leetcode_username"]

HEADERS = {
    "Content-Type": "application/json",
    "Referer": "https://leetcode.com",
    "User-Agent": "Mozilla/5.0"
}


def graphql(query: str, variables: dict):
    resp = requests.post(
        GRAPHQL_URL,
        headers=HEADERS,
        json={"query": query, "variables": variables},
        timeout=15
    )
    resp.raise_for_status()
    data = resp.json()
    if "errors" in data:
        raise RuntimeError(f"GraphQL error: {data['errors']}")
    return data["data"]


def get_question_info(slug: str):
    query = """
    query questionData($titleSlug: String!) {
      question(titleSlug: $titleSlug) {
        title
        difficulty
      }
    }
    """
    data = graphql(query, {"titleSlug": slug})["question"]
    if not data:
        return slug.replace("-", " ").title(), "Unknown"
    return data["title"], data["difficulty"]


def main():
    root = "solutions"
    if not os.path.isdir(root):
        print("No solutions folder found. Run fetch_leetcode.py first.")
        return

    for slug in os.listdir(root):
        folder = os.path.join(root, slug)
        if not os.path.isdir(folder):
            continue

        print(f"📄 Generating README for {slug}")
        try:
            title, difficulty = get_question_info(slug)
        except Exception as e:
            print(f"  ⚠️ Failed to fetch question info: {e}")
            title = slug.replace("-", " ").title()
            difficulty = "Unknown"

        readme_path = os.path.join(folder, "README.md")
        with open(readme_path, "w") as f:
            f.write(f"# {title}\n\n")
            f.write(f"**Difficulty:** `{difficulty}`\n\n")
            f.write(f"🔗 [View on LeetCode](https://leetcode.com/problems/{slug}/)\n\n")
            f.write("---\n")
            f.write(f"_Auto-generated by Greenery-JS2334 sync bot._\n")

    print("✅ Problem READMEs generated.")


if __name__ == "__main__":
    main()
